### ISSUE TITLE
add 2 links to the wiki

### ISSUE THREAD

**Issue by VladimirAlexiev** [UICrail/SemanticRSM#16]
Add https://github.com/UICrail/SemanticRSM/wiki in two places:
- project description, so it appears on the right side where it says 
**About**
RSM refoundation, based on direct RDF/OWL modelling
- https://github.com/UICrail/SemanticRSM#wiki

**Comment by Airy59** [comment]
Thanks (blagodaria) for your advice!
Will be taken into account ASAP

**Comment by tanepierre** [comment]
Thanks, proceeded with the suggestion!

**Comment by tanepierre** [comment]
closed with https://github.com/UICrail/SemanticRSM/commit/9762aec712a6b04a5eb727d40ec3326621a30efc
