### ISSUE TITLE
`ifc_adapter:` lacks separator

### ISSUE THREAD

**Issue by VladimirAlexiev** [UICrail/SemanticRSM#17]
https://raw.githubusercontent.com/UICrail/SemanticRSM/refs/heads/main/Code/Import/SD1_import/scheibenberg.ttl:
```
@prefix ifc_adapter: <https://cdm.ovh/adapters/ifcowl_rsm> .
```
This lacks a separator at the end, so ontology terms in this namespace won't have proper local names. 
Eg `ifc_adapter:hasIfcAlignment` is expanded to https://cdm.ovh/adapters/ifcowl_rsmhasIfcAlignment

**Comment by Airy59** [comment]
Fixed in cdm_namespaces.py.
