### ISSUE TITLE
Why do we need two DataProperties IntrinsincCoordinate and LinearElementLength

### ISSUE THREAD

**Issue by gatemezing** [UICrail/SemanticRSM#7]
In the current version of the topology.ttl file, there are new defined datatypes `:IntrinsincCoordinate `and `:LinearElementLength`.
Do we need to create those custom datatypes?

**Comment by Airy59** [comment]
Those custom datatypes are **not necessary**. They **may** be needed.

Both could be replaced by xsd:decimal, with SHACL constraints for [0,1] and >= 0, respectively. That would be the down-to-earth approach.

The fact that a length must be expressed in some unit to make sense could then be expressed in the definition of property nominalLength (using rdfs:comment "this nominal length is expressed in meter"). Alternatively, length could be expressed as of type :Measure, coming with a value and a unit, etc. So there is a number of possible choices.

More generally:
- intrinsic coordinate could use any totally ordered and bounded set (finite or not)
- linear element length can be any kind of measure over the linear element

Introducing those two datatypes would ease linking with other models that would use their own types, such as "length must be an integer value with unit millimeter" or "length is a decimal value expressed in meter", or other definitions made to taste.

The derived models (ontologies) could also define their subproperties accordingly.

Neutrality (implementation-independence) comes at a price. It should not become a deterrent. This is why I leave the issue open.

**Comment by Airy59** [comment]
Types removed. This is partly due to the usage of geosparql properties that use plain xsd:double (hasMetricLength). May suffice after all, at least in the topology context.
