### ISSUE TITLE
Purpose of LinearElementPart w.r.t. NetElement

### ISSUE THREAD

**Issue by gatemezing** [UICrail/SemanticRSM#8]
The concept :LinearElementPart doest not appear in the drawing.

**Comment by Airy59** [comment]
Depends on the drawing; in the wiki it appears. Sorry for inconvenience in case things are out of sync.

Concerning the purpose: a LinearElementPart is only used for composition, e.g. to cut out a station area and turn it into one big non-linear element. As you will see from the model, a linear element part is NOT a linear element, nor a net element. Hence it is not related to ports and navigabilities.

This design choice is of course disputable. Purpose was to avoid polluting the MICRO level topology with artefacts only needed for the MESO level.

**Comment by Airy59** [comment]
no further discussion = closed.
